services:
  newsletter:
    build:
      context: .
      dockerfile: Dockerfile
    image: kaffe-letter:latest
    command: ["--mode", "server"]
    env_file:
      - path: .env
        required: false
    ports:
      - "8080:8080"
    volumes:
      - kaffe-letter-data:/app/data
    restart: "no"

volumes:
  kaffe-letter-data:
