services:
  newsletter:
    build:
      context: .
      dockerfile: Dockerfile
    image: kaffe-letter:latest
    command: ["--mode", "server"]
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data
    restart: "no"
